version: '3.7'

services:
  icecast:
    image: vimagick/icecast
    container_name: icecast_interoceanica # <-- Nombre único para esta radio
    volumes:
      - ./icecast.xml:/etc/icecast.xml
    # Ya no necesitamos las variables de LETSENCRYPT aquí
    restart: unless-stopped
    networks:
      - proxy-net

networks:
  proxy-net:
    external:
      name: nginx-proxy-net # Se conecta a la misma red compartida
