version: '3.7'

services:
  # --- NGINX PROXY MANAGER (Todo en uno) ---
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      # Puertos públicos para el tráfico web
      - '80:80'
      - '443:443'
      # Puerto para acceder a la interfaz de administración
      - '8181:81'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - proxy-net

networks:
  proxy-net:
    external:
      name: nginx-proxy-net # Usa la red externa que ya creamos

volumes:
  data:
  letsencrypt: