version: '3.7'

services:
  # --- PROXY AUTOMÁTICO DE NGINX ---
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-net
    restart: always

  # --- COMPAÑERO PARA CERTIFICADOS SSL AUTOMÁTICOS ---
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    # --- ESTA ES LA SECCIÓN AÑADIDA ---
    environment:
      # Le decimos explícitamente cuál es el contenedor del proxy
      - NGINX_PROXY_CONTAINER=nginx-proxy
    # --- FIN DE LA SECCIÓN AÑADIDA ---
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-net
    restart: always

volumes:
  certs:
  vhost:
  html:

networks:
  proxy-net:
    external:
      name: nginx-proxy-net
